import {Content} from "../common/content.slint";
import { HorizontalBox , Button, TextEdit, ListView} from "std-widgets.slint";
import {CompressGlobal} from "../model/compress_global.slint";
import {ImageList} from "../widgets/image_list.slint";
import { FFButton } from "../widgets/feifei_button.slint";

export component CompressImage inherits Rectangle { 

    Content {
        Rectangle {
            VerticalLayout {
                HorizontalBox { 
                    alignment: LayoutAlignment.start;
                    FFButton {
                        button-name: "选择文件夹";
                        ff-height: 38px;
                        clicked => {
                            CompressGlobal.open-folder();
                        }
                    }
                    Rectangle {
                        width: 670px;
                        height: 40px;
                        border-color: #CCCCCC;
                        border-width: 1px;
                        border-radius: 3px;
                        Text {
                            width: 650px;
                            horizontal-alignment: TextHorizontalAlignment.left;
                            font-size: 18px;
                            text: CompressGlobal.compress-path;
                            color: #5e5d5d;
                        }
                    }
                    Rectangle {
                        width: 5px;
                    }
                    Rectangle {
                        FFButton {
                            button-name: "批量处理";
                            ff-height: 38px;
                            clicked => {
                                CompressGlobal.compress-batching();
                            }
                        }
                    }
                    
                }
                ListView {
                    for image in CompressGlobal.image-list : ImageList{
                        name: image.name;
                        status: image.status;
                    }
                }
            }
            
        }
    }

}

