import {Content} from "../common/content.slint";
import { HorizontalBox , Button, TextEdit, ListView} from "std-widgets.slint";
import {CompressGlobal} from "../model/compress_global.slint";
import {ImageList} from "../widgets/image_list.slint";

export component CompressImage inherits Rectangle { 

    callback open();

    Content {
        Rectangle {
            VerticalLayout {
                HorizontalBox { 
                    alignment: LayoutAlignment.start;
                    Button {
                        width: 100px;
                        height: 30px;
                        text: "选择文件夹";
                        clicked => {
                            open();
                        }
                    }
                    Rectangle {
                        width: 670px;
                        height: 30px;
                        border-color: #CCCCCC;
                        border-width: 1px;
                        border-radius: 3px;
                        Text {
                            width: 650px;
                            horizontal-alignment: TextHorizontalAlignment.left;
                            font-size: 15px;
                            text: CompressGlobal.compress-path;
                            color: #5e5d5d;
                        }
                    }
                    Rectangle {
                        width: 5px;
                    }
                    Rectangle {
                        Button {
                            text: "开始处理";
                            width: 100px;
                            height: 30px;
                        }
                    }
                    
                }
                ListView {
                    width: 100%;
                    for image in CompressGlobal.image-list : ImageList{
                        name: image.name;
                        status: image.status;
                    }
                }
            }
            
        }
    }

}

