import { MenuButton,Menu } from "../common/menu.slint";
import { CompressImage } from "./compress_image.slint";
import { FormatImage } from "./format_image.slint";
import { About } from "./about.slint";
import { VersionUpgrade } from "./version_upgrade.slint";

//主要显示页面
export component Home inherits Rectangle{

    callback clicked(int);

    out property <int> current-page: 0;
    callback compress_open();

    VerticalLayout {
        //菜单部分
        HorizontalLayout {
            padding-top: 10px;
            padding-left: 10px;
            padding-right: 10px;
            height: 43px;
            Menu{
                current-page <=> current-page;
            }
        }
        Rectangle {
            height: 10px;
        }
        //内容部分
        HorizontalLayout {
            if (current_page == 0) :CompressImage{
                open => {
                    compress_open();
                }
            }
            if(current-page == 1) :FormatImage{}
            if(current-page == 2) :About {}
            if(current-page == 3) :VersionUpgrade{}
        }
    }

}


