


export component MenuButton inherits Rectangle { 

    
    in-out property <string> button-name;
    //0 表示正常状态  1表示禁用状态
    in-out property <int> status:0;
    callback switch-page();

    area := TouchArea {
        clicked => {
            switch-page()
        }
    }

    VerticalLayout {
        Rectangle {
            width: 140px;
            height: 40px;
            border-radius: 3px;
            background: status==0?area.pressed?Colors.rgb(13,102,171):Colors.rgb(13,136,228):Colors.rgb(194,194,194);
            drop-shadow-color: black;
            drop-shadow-offset-x: 3px;
            drop-shadow-offset-y: 3px;
            drop-shadow-blur: 10px;
            
            Text {
                text: button-name;
                color: Colors.white;
                font-size: 14px;
            }
            
        }
    }
    

}

export component Menu inherits HorizontalLayout{

    in-out property <int> current-page: 0;

    MenuButton {
        button-name: @tr("Menu" => "compress pictures");
        switch-page => {current-page = 0}
    }
    MenuButton {
        button-name: @tr("format conversion");
        switch-page => {current-page = 1;}
    }
    MenuButton {
        button-name: @tr("About Software");
        switch-page => {current-page = 2;}
    }
    MenuButton {
        button-name: @tr("Settings");
        switch-page => {current-page = 3;}
    }
}




