import {FFButton} from "../widgets/feifei_button.slint";
import {FFTheme} from "../theme.slint";
import { SystemGlobal } from "../model/system_global.slint";

export component Menu inherits Rectangle{

    in-out property <int> current-page: 0;

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        
        FFButton {
            button-name: "压缩图片";
            clicked => {current-page = 0;}
        }
        FFButton {
            button-name: "格式转换";
            clicked => {current-page = 1;}
        }
        FFButton {
            button-name: "关于软件";
            clicked => {current-page = 2;}
        }
        FFButton {
            button-name: "系统设置";
            clicked => {current-page = 3;}
        }
        FFButton {
            button-name: "主题切换";
            clicked => {
                if(FFTheme.theme == FFTheme.bright){
                    FFTheme.theme = FFTheme.dark;
                }else{
                    FFTheme.theme = FFTheme.bright;
                }
            }
        }
        FFButton {
            button-name: "关闭程序";
            clicked => {
                SystemGlobal.system-close();
            }
        }
        
    }
    
}




