


export component MenuButton inherits Rectangle { 

    
    in-out property <string> button-name;
    //0 表示正常状态  1表示禁用状态
    in-out property <int> status:0;

    area := TouchArea {
        clicked => {
            
        }
    }

    VerticalLayout {
        Rectangle {
            width: 120px;
            height: 50px;
            border-radius: 3px;
            background: status==0?area.pressed?Colors.rgb(13,102,171):Colors.rgb(13,136,228):Colors.rgb(194,194,194);
            drop-shadow-color: black;
            drop-shadow-offset-x: 3px;
            drop-shadow-offset-y: 3px;
            drop-shadow-blur: 10px;
            
            Text {
                text: button-name;
                color: Colors.white;
                font-size: 14px;
            }
            
        }
        Rectangle {height: 2px;}
    }
    

}

export component Menu inherits Rectangle{

    width: 300px;
    height: 300px;

    Rectangle {
        width: 120px;
        VerticalLayout {
            MenuButton {
                button-name: "格式转换";
            }
            MenuButton {
                button-name: "压缩图片";
            }
            MenuButton {
                button-name: "关于软件";
            }
            MenuButton {
                button-name: "版本更新";
            }
        }
        
    }
}


export component MyApp {
    width: 200px;
    height: 100px;
    Rectangle {
        width: 100px;
        height: 50px;
        border-radius: 10px;
        background: blue;
        drop-shadow-color: black;
        drop-shadow-offset-x: 10px;
        drop-shadow-offset-y: 10px;
        drop-shadow-blur: 10px;
    }
}



