
import {FFTheme} from "../theme.slint";
import { Button } from "std-widgets.slint";
export component ImageList inherits Rectangle{ 

    in-out property <string> name;
    in-out property <int> status;
    in-out property <string> button-name;

    area := TouchArea {}

    Rectangle {
        height: 40px;
        background: area.has-hover?FFTheme.theme.hover-content-background-color:FFTheme.theme.content-background-color;
        HorizontalLayout {
            alignment: LayoutAlignment.space-around;
            height: 40px;
            Rectangle {
                height: 40px;
                width: 400px;
                Text {
                    horizontal-alignment: TextHorizontalAlignment.left;
                    width: 400px;
                    text: name;
                    font-size: 15px;
                    overflow: TextOverflow.elide;
                    color: FFTheme.theme.content-text-color;
                }
            }
            Rectangle {
                height: 40px;
                width: 100px;
                Text {
                    width: 100px;
                    text: status==0?"等待":status==1?"处理中":"完成";
                    font-size: 15px;
                    wrap: TextWrap.word-wrap;
                    color: FFTheme.theme.content-text-color;
                }
            }
        }
    }
    
}

