
export struct ImageList {
    name: string,
    path: string,
    status: int
}


export global CompressGlobal {
    //选择的文件夹路径
    in-out property <string> compress-path : "e://rust";

    //存放数据
    in-out property <[ImageList]> image-list : [
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0},
        {name:"1",path:"",status:0}
    ];
}